include:
  - project: 'next-swr/platform/ci/ci-base'
    ref: master
    file: '/github-ci/docker/generic/.github-ci-template.yml'

variables:
  APP_PORT: 3000
  APP_ENVIRONMENT_SECRETS: "[\"next-swr-auth\"]"

build-image:
  variables:
    DOCKERFILE: Dockerfile.dev