include:
  - project: 'moonpibank/platform/ci/ci-base'
    ref: master
    file: '/gitlab-ci/docker/generic/.gitlab-ci-template.yml'

variables:
  APP_PORT: 3000
  APP_ENVIRONMENT_SECRETS: "[\"next-swr-auth\"]"

build-image:
  variables:
    DOCKERFILE: Dockerfile.dev